# forms.py
from django import forms

class ClimateForm(forms.Form):
    country = forms.ChoiceField(choices=[
        ('USA', 'USA'),
        ('Canada', 'Canada'),
        ('Australia', 'Australia'),
        ('Norway', 'Norway'),
        ('Sweden', 'Sweden'),
        ('Finland', 'Finland'),
        ('Russia', 'Russia'),
        ('Iceland', 'Iceland'),
        ('Greenland', 'Greenland'),
        ('Svalbard and Jan Mayen', 'Svalbard and Jan Mayen'),
        ('Mongolia', 'Mongolia'),
        ('Heard Island and McDonald Islands', 'Heard Island and McDonald Islands'),
        ('Kyrgyzstan', 'Kyrgyzstan'),
        ('Tajikistan', 'Tajikistan'),
        ('French Southern and Antarctic Lands', 'French Southern and Antarctic Lands'),
        ('Saint Pierre and Miquelon', 'Saint Pierre and Miquelon'),
        ('Estonia', 'Estonia'),
        ('Switzerland', 'Switzerland'),
        ('Faroe Islands', 'Faroe Islands'),
        ('Latvia', 'Latvia'),
        ('North Korea', 'North Korea'),
        ('Kazakhstan', 'Kazakhstan'),
        ('Lithuania', 'Lithuania'),
        ('Austria', 'Austria'),
        ('Belarus', 'Belarus'),
        ('Liechtenstein', 'Liechtenstein'),
        ('Armenia', 'Armenia'),
        ('Andorra', 'Andorra'),
        ('Czech Republic', 'Czech Republic'),
        ('Poland', 'Poland'),
        ('Slovakia', 'Slovakia'),
        ('Georgia', 'Georgia'),
        ('United Kingdom', 'United Kingdom'),
        ('Ukraine', 'Ukraine'),
        ('Chile', 'Chile'),
        ('Isle of Man', 'Isle of Man'),
        ('Ireland', 'Ireland'),
        ('Slovenia', 'Slovenia'),
        ('Montenegro', 'Montenegro'),
        ('Luxembourg', 'Luxembourg'),
        ('Kosovo', 'Kosovo'),
        ('Romania', 'Romania'),
        ('Bosnia and Herzegovina', 'Bosnia and Herzegovina'),
        ('Bhutan', 'Bhutan'),
        ('New Zealand', 'New Zealand'),
        ('Netherlands', 'Netherlands'),
        ('Belgium', 'Belgium'),
        ('North Macedonia', 'North Macedonia'),
        ('Moldova', 'Moldova'),
        ('Bulgaria', 'Bulgaria'),
        ('Serbia', 'Serbia'),
        ('Hungary', 'Hungary'),
        ('France', 'France'),
        ('Turkey', 'Turkey'),
        ('Japan', 'Japan'),
        ('Croatia', 'Croatia'),
        ('Guernsey', 'Guernsey'),
        ('South Korea', 'South Korea'),
        ('Jersey', 'Jersey'),
        ('Lesotho', 'Lesotho'),
        ('Albania', 'Albania'),
        ('San Marino', 'San Marino'),
        ('Brazil', 'Brazil'),
        ('South Africa', 'South Africa'),
        ('Argentina', 'Argentina'),
        ('Colombia', 'Colombia'),
        ('Venezuela', 'Venezuela'),
        ('Ecuador', 'Ecuador'),
        ('Bolivia', 'Bolivia'),
        ('Paraguay', 'Paraguay'),
        ('Uruguay', 'Uruguay'),
        ('Panama', 'Panama'),
        ('Belize', 'Belize'),
        ('Yemen', 'Yemen'),
        ('Cuba', 'Cuba'),
        ('Nicaragua', 'Nicaragua'),
        ('Central African Republic', 'Central African Republic'),
        ('Liberia', 'Liberia'),
        ('El Salvador', 'El Salvador'),
        ('Gabon', 'Gabon'),
        ('Kenya', 'Kenya'),
        ('Puerto Rico', 'Puerto Rico'),
        ('India', 'India'),
        ('Pakistan', 'Pakistan'),
        ('Afghanistan', 'Afghanistan'),
        ('Iran', 'Iran'),
        ('Iraq', 'Iraq'),
        ('Saudi Arabia', 'Saudi Arabia'),
        ('Oman', 'Oman'),
        ('United Arab Emirates', 'United Arab Emirates'),
        ('Kuwait', 'Kuwait'),
        ('Morocco', 'Morocco'),
        ('Tunisia', 'Tunisia'),
        ('Libya', 'Libya'),
        ('Egypt', 'Egypt'),
        ('Israel', 'Israel'),
        ('Jordan', 'Jordan'),
        ('Qatar', 'Qatar'),
        ('Burkina Faso', 'Burkina Faso'),
        ('Mali', 'Mali'),
        ('Aruba', 'Aruba'),
        ('Senegal', 'Senegal'),
        ('Mauritania', 'Mauritania'),
        ('Tokelau', 'Tokelau'),
        ('Tuvalu', 'Tuvalu'),
        ('Djibouti', 'Djibouti'),
        ('Curacao', 'Curacao'),
        ('Gambia', 'Gambia'),
        ('Maldives', 'Maldives'),
        ('Niger', 'Niger'),
        ('Benin', 'Benin'),
        ('Marshall Islands', 'Marshall Islands'),
        ('Guinea-Bissau', 'Guinea-Bissau'),
        ('South Sudan', 'South Sudan'),
        ('Sudan', 'Sudan'),
        ('Palau', 'Palau'),
        ('Nauru', 'Nauru'),
        ('Cayman Islands', 'Cayman Islands'),
        ('Guam', 'Guam'),
        ('Kiribati', 'Kiribati'),
        ('Anguilla', 'Anguilla'),
        ('Saint Martin', 'Saint Martin'),
        ('Sint Maarten', 'Sint Maarten'),
        ('Bahrain', 'Bahrain'),
        ('Singapore', 'Singapore'),
        ('Ghana', 'Ghana'),
        ('Chad', 'Chad'),
    ],    widget=forms.Select(attrs={'class': 'transparent-dropdown'}))

    year = forms.IntegerField(min_value=2024, max_value=2100, label='Year',widget=forms.NumberInput(attrs={'class': 'transparent-input'})
)

class ClimateGraphForm(forms.Form):
    country = forms.ChoiceField(choices=[
        ('USA', 'USA'),
        ('Canada', 'Canada'),
        ('Australia', 'Australia'),
        ('Norway', 'Norway'),
        ('Sweden', 'Sweden'),
        ('Finland', 'Finland'),
        ('Russia', 'Russia'),
        ('Iceland', 'Iceland'),
        ('Greenland', 'Greenland'),
        ('Svalbard and Jan Mayen', 'Svalbard and Jan Mayen'),
        ('Mongolia', 'Mongolia'),
        ('Heard Island and McDonald Islands', 'Heard Island and McDonald Islands'),
        ('Kyrgyzstan', 'Kyrgyzstan'),
        ('Tajikistan', 'Tajikistan'),
        ('French Southern and Antarctic Lands', 'French Southern and Antarctic Lands'),
        ('Saint Pierre and Miquelon', 'Saint Pierre and Miquelon'),
        ('Estonia', 'Estonia'),
        ('Switzerland', 'Switzerland'),
        ('Faroe Islands', 'Faroe Islands'),
        ('Latvia', 'Latvia'),
        ('North Korea', 'North Korea'),
        ('Kazakhstan', 'Kazakhstan'),
        ('Lithuania', 'Lithuania'),
        ('Austria', 'Austria'),
        ('Belarus', 'Belarus'),
        ('Liechtenstein', 'Liechtenstein'),
        ('Armenia', 'Armenia'),
        ('Andorra', 'Andorra'),
        ('Czech Republic', 'Czech Republic'),
        ('Poland', 'Poland'),
        ('Slovakia', 'Slovakia'),
        ('Georgia', 'Georgia'),
        ('United Kingdom', 'United Kingdom'),
        ('Ukraine', 'Ukraine'),
        ('Chile', 'Chile'),
        ('Isle of Man', 'Isle of Man'),
        ('Ireland', 'Ireland'),
        ('Slovenia', 'Slovenia'),
        ('Montenegro', 'Montenegro'),
        ('Luxembourg', 'Luxembourg'),
        ('Kosovo', 'Kosovo'),
        ('Romania', 'Romania'),
        ('Bosnia and Herzegovina', 'Bosnia and Herzegovina'),
        ('Bhutan', 'Bhutan'),
        ('New Zealand', 'New Zealand'),
        ('Netherlands', 'Netherlands'),
        ('Belgium', 'Belgium'),
        ('North Macedonia', 'North Macedonia'),
        ('Moldova', 'Moldova'),
        ('Bulgaria', 'Bulgaria'),
        ('Serbia', 'Serbia'),
        ('Hungary', 'Hungary'),
        ('France', 'France'),
        ('Turkey', 'Turkey'),
        ('Japan', 'Japan'),
        ('Croatia', 'Croatia'),
        ('Guernsey', 'Guernsey'),
        ('South Korea', 'South Korea'),
        ('Jersey', 'Jersey'),
        ('Lesotho', 'Lesotho'),
        ('Albania', 'Albania'),
        ('San Marino', 'San Marino'),
        ('Brazil', 'Brazil'),
        ('South Africa', 'South Africa'),
        ('Argentina', 'Argentina'),
        ('Colombia', 'Colombia'),
        ('Venezuela', 'Venezuela'),
        ('Ecuador', 'Ecuador'),
        ('Bolivia', 'Bolivia'),
        ('Paraguay', 'Paraguay'),
        ('Uruguay', 'Uruguay'),
        ('Panama', 'Panama'),
        ('Belize', 'Belize'),
        ('Yemen', 'Yemen'),
        ('Cuba', 'Cuba'),
        ('Nicaragua', 'Nicaragua'),
        ('Central African Republic', 'Central African Republic'),
        ('Liberia', 'Liberia'),
        ('El Salvador', 'El Salvador'),
        ('Gabon', 'Gabon'),
        ('Kenya', 'Kenya'),
        ('Puerto Rico', 'Puerto Rico'),
        ('India', 'India'),
        ('Pakistan', 'Pakistan'),
        ('Afghanistan', 'Afghanistan'),
        ('Iran', 'Iran'),
        ('Iraq', 'Iraq'),
        ('Saudi Arabia', 'Saudi Arabia'),
        ('Oman', 'Oman'),
        ('United Arab Emirates', 'United Arab Emirates'),
        ('Kuwait', 'Kuwait'),
        ('Morocco', 'Morocco'),
        ('Tunisia', 'Tunisia'),
        ('Libya', 'Libya'),
        ('Egypt', 'Egypt'),
        ('Israel', 'Israel'),
        ('Jordan', 'Jordan'),
        ('Qatar', 'Qatar'),
        ('Burkina Faso', 'Burkina Faso'),
        ('Mali', 'Mali'),
        ('Aruba', 'Aruba'),
        ('Senegal', 'Senegal'),
        ('Mauritania', 'Mauritania'),
        ('Tokelau', 'Tokelau'),
        ('Tuvalu', 'Tuvalu'),
        ('Djibouti', 'Djibouti'),
        ('Curacao', 'Curacao'),
        ('Gambia', 'Gambia'),
        ('Maldives', 'Maldives'),
        ('Niger', 'Niger'),
        ('Benin', 'Benin'),
        ('Marshall Islands', 'Marshall Islands'),
        ('Guinea-Bissau', 'Guinea-Bissau'),
        ('South Sudan', 'South Sudan'),
        ('Sudan', 'Sudan'),
        ('Palau', 'Palau'),
        ('Nauru', 'Nauru'),
        ('Cayman Islands', 'Cayman Islands'),
        ('Guam', 'Guam'),
        ('Kiribati', 'Kiribati'),
        ('Anguilla', 'Anguilla'),
        ('Saint Martin', 'Saint Martin'),
        ('Sint Maarten', 'Sint Maarten'),
        ('Bahrain', 'Bahrain'),
        ('Singapore', 'Singapore'),
        ('Ghana', 'Ghana'),
        ('Chad', 'Chad'),
    ],   widget=forms.Select(attrs={'class': 'transparent-dropdown'}))
    start_year = forms.IntegerField(min_value=2024, max_value=2100, label='start Year', widget=forms.NumberInput(attrs={'class': 'transparent-input'}))
    end_year = forms.IntegerField(min_value=2024, max_value=2100, label='End Year', widget=forms.NumberInput(attrs={'class': 'transparent-input'}))