# Generated by Django 5.1.1 on 2024-09-07 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_change', '0002_climategraphs_alter_climatedata_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climatedata',
            name='country',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
